name: Check Video Stream

on: 
  schedule: 
    - cron: "0 0 * * *"
  release:
    types: [created]
  workflow_dispatch: # Put here!!
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Search address from fofa
        run: |
          query="udpxy\" && region=\"Shanghai\""
          result=$(curl -s "https://fofa.info/result?q=$query")
          url=$(jq -r '.results[0].cert_domain' <<< "$result")

      - name: Check stream accessibility
        run: |
          curl -I "$url/udp/239.45.3.146:5140"
          if [[ $? -eq 0 ]]; then
            echo "Stream accessible"
          else  
            echo "Stream not accessible" 
          fi

      - name: Notify on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" -d "{\"content\":\"Check failed\"}" ${{ secrets.DISCORD_WEBHOOK }}
