name: Check Video Stream 

on:
  schedule:
    - cron: "0 0 * * *"
  release:
    types: [created]
  workflow_dispatch: # Put here!!
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Search address from fofa
        run: |
          query='udpxy" && region="Shanghai"'
          encoded_query=$(echo -n "$query" | base64)

          result=$(curl -s "https://fofa.info/result?qbase64=$encoded_query")
          url=$(jq -r '.results[0].cert_domain' <(echo "$result"))

      - name: Check stream accessibility 
        run: |
          curl -I "$url/udp/239.45.3.146:5140" 
          if [[ $? -eq 0 ]]; then
            echo "Stream is accessible"
            echo "$url" >> stream_url.txt
          else
            echo "Stream is not accessible"  
          fi

      - name: Notify
        if: failure()
        uses: serot/discord-webhook-action@v2
        env:  
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Video stream check failed! URL is $url"
